// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartBuilding;

#nullable disable

namespace smartBuilding.Migrations
{
    [DbContext(typeof(SmartBuildingDb))]
    [Migration("20220528140310_Rework2")]
    partial class Rework2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("smartBuilding.Models.HomeHumidity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Humidity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasureDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_HomeHumidityId");

                    b.ToTable("Humidities");
                });

            modelBuilder.Entity("smartBuilding.Models.HomeTemperature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_HomeTemperatureId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("smartBuilding.Models.HomeWaterLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_HomeWaterLevelId");

                    b.ToTable("WaterLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
