// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smartBuilding;

#nullable disable

namespace smartBuilding.Migrations
{
    [DbContext(typeof(SmartBuildingDb))]
    partial class SmartBuildingDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("smartBuilding.Models.HomeLight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TurnedOn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_HomeLightId");

                    b.ToTable("HomeLights");
                });

            modelBuilder.Entity("smartBuilding.Models.HomePresences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseholderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPresent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseholderId");

                    b.ToTable("HomePresences");
                });

            modelBuilder.Entity("smartBuilding.Models.HomeTemperature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeasureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_HomeTemperatureId");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("smartBuilding.Models.Householders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentifyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homeholders");
                });

            modelBuilder.Entity("smartBuilding.Models.HomePresences", b =>
                {
                    b.HasOne("smartBuilding.Models.Householders", "Householder")
                        .WithMany("HomePresences")
                        .HasForeignKey("HouseholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Householder");
                });

            modelBuilder.Entity("smartBuilding.Models.Householders", b =>
                {
                    b.Navigation("HomePresences");
                });
#pragma warning restore 612, 618
        }
    }
}
